### ISSUE TITLE
Error when I select a "Load condition" with "Multiple" and select several or even just one option.

### ISSUE THREAD

**Issue by gotex007** [Snakybo/Clicked#208] opened 2024-08-03 23:35 UTC
### Describe the bug

It seems to happen with any of the options to select multiple conditions like classes, specs, instance types, etc. The error seems to says it's ElvUI triggering it but it actively happens specifically in Clicked and Clicked is mentioned in the log so I'm reporting it here.

### Clicked Version

1.15.3b

### World of Warcraft Flavor

Retail

### Tried with only Clicked enabled

- [ ] Yes
- [ ] No

### Lua Errors

24x .../ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua:173: attempt to index local 'widget' (a nil value)
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:173: in function `Release'
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:468: in function `ReleaseChildren'
[string "@Clicked/Config/Bindings.lua"]:3237: in function <Clicked/Config/Bindings.lua:3233>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <.../ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Clicked/Widgets/AceGUIContainer-ClickedTreeGroup.lua"]:1325: in function `Select'
[string "@Clicked/Widgets/AceGUIContainer-ClickedTreeGroup.lua"]:1335: in function `SelectByValue'
[string "@Clicked/Widgets/AceGUIContainer-ClickedTreeGroup.lua"]:1078: in function `ConstructTree'
[string "@Clicked/Config/Bindings.lua"]:3383: in function `BindingConfig_Redraw'
[string "@Clicked/Core/BindingProcessor.lua"]:638: in function <Clicked/Core/BindingProcessor.lua:600>
[string "@Clicked/Core/BindingProcessor.lua"]:652: in function `ReloadBinding'
...
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown.lua"]:369: in function <...re/Ace3/AceGUI-3.0/widgets/AceGUIWidget-DropDown.lua:366>
[string "=[C]"]: in function `Hide'
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:176: in function `Release'
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:468: in function `ReleaseChildren'
[string "@Clicked/Config/Bindings.lua"]:3237: in function <Clicked/Config/Bindings.lua:3233>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <.../ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Clicked/Widgets/AceGUIContainer-ClickedTreeGroup.lua"]:1304: in function `SetSelected'
[string "@Clicked/Widgets/AceGUIContainer-ClickedTreeGroup.lua"]:466: in function <...Clicked/Widgets/AceGUIContainer-ClickedTreeGroup.lua:460>

Locals:
self = <table> {
 objPools = <table> {
 }
 WidgetBase = <table> {
 }
 counts = <table> {
 }
 FocusedWidget = <table> {
 }
 LayoutRegistry = <table> {
 }
 tooltip = AceGUITooltip {
 }
 WidgetRegistry = <table> {
 }
 WidgetVersions = <table> {
 }
 WidgetContainerBase = <table> {
 }
}
widget = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'widget' (a nil value)"
UIParent = UIParent {
 variablesLoaded = true
 Tabs = <table> {
 }
 PixelSnapDisabled = true
 firstTimeLoaded = 1
}

### Reproduction Steps

1. Select a macro
2. Change a load condition to "Multiple" (e.g. class)
3. Select multiple options or even unselect the default option and select it again (e.g. hunter, paladin, and priest)
4. Click on any other macro or group
5. Error triggers but otherwise doesn't seem to break or affect anything.

**Comment by gotex007** [comment] 2024-08-03 23:50
This might be related to https://github.com/Snakybo/Clicked/issues/207 as it seems that in step 4 of my reproduction steps above, if you instead select a tab (except Action?) in the same macro that is the tab that gets stuck and overlayed until a reload.

Example steps for the weird overlay problem:

1. Click "New" (happens with any macro, does not need to be a new one)
2. Click "Cast a spell" (any macro type appears to work)
3. Click "Load conditions"
4. Click "Race" twice to make it "Multiple" (any tickbox with "Multiple" appears to work)
5. Select any combination of options you want, so long as you select a new one or unselect the default and select it again
6. Click on a different tab in that same macro, as long as it is not "Action"
7. The tab you selected is now overlayed as described in https://github.com/Snakybo/Clicked/issues/207 when you look at any tab in any macro, but not in the "New" menu or at a "Group"

I'll edit my ticket there to reflect my discovery of intentional reproduction.

**Comment by Snakybo** [comment] 2024-08-04 21:03
I cannot reproduce this, does it happen consistently? Can you try it without other addons enabled?

**Comment by gotex007** [comment] 2024-08-04 23:59
Do you use ElvUI? It's certainly an interaction with ElvUI based on the error. I just chose to post it here because it doesn't happen with other addons and also I hate dealing with Repopoc and the ElvUI posse.

**Comment by Snakybo** [comment] 2024-08-06 19:53
I do use ElvUI yeah

**Comment by gotex007** [comment] 2024-08-07 23:21
I don't know then. I have a 100% reproduction rate with both issues. I just did it now with both of today's Clicked and ElvUI updates. Also tested it with only ElvUI and Clicked enabled and I still replicate it with 100% success.

**Comment by gotex007** [comment] 2024-08-07 23:40
I recorded and uploaded me replicating [both issues #207 and #208](https://youtu.be/opfVeB6H6yA)

**Comment by Snakybo** [comment] 2024-08-08 10:05
Oh yeah, I see it now too, that video helped 😄

So I think it's a library issue, I'll try to get that resolved. But as a workaround, try closing the dropdown prior to switching pages

**Comment by gotex007** [comment] 2024-08-09 01:34
Yeah that is a workaround and it's not often somebody does go directly from the multi-select dropdown box to another macro or tab as they would probably go to another load option, which is why it took me some time to actually figure out exactly how to reproduce it.

**Comment by Snakybo** [comment] 2024-08-29 23:46
Fixed in 1.16.0 :)

**Closed by Snakybo** 2024-08-29 23:46 UTC
