### ISSUE TITLE
The Wow Client crashes when only this addon is enabled

### ISSUE THREAD

**Issue by rbpaiett** [Snakybo/Clicked#237] opened 2024-09-25 04:59 UTC
### Describe the bug

I expected the game to load and it didn't.

### Clicked Version

Clicked 1.16.8

### World of Warcraft Flavor

Classic Era

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Lua Errors

I'm not able to get an Lua error because the game crashes while loading.  I do get the blizz error however:

https://imgur.com/JNxRjPn

### Reproduction Steps

1.  Enable the Clicked addon by itself.
2.  Attempt to logon

### Last Working Version

Clicked 1.16.7

### Screenshots

![JNxRjPn](https://github.com/user-attachments/assets/218b32ba-2675-4271-9208-de8c1da5106b)

### Debug Output

I couldn't even get into the game to generate a dump file.

**Comment by Snakybo** [comment] 2024-09-25 22:00
I can't reproduce this — can you send me your SavedVariables file?

**Comment by Snakybo** [comment] 2024-09-25 22:46
Seems like a bug in-game, I reported it here: https://github.com/Stanzilla/WoWUIBugs/issues/662

In the meantime, I'll try a workaround to prevent it from crashing

**Comment by Snakybo** [comment] 2024-09-25 22:58
_should_ be resolved in 1.16.9

**Closed** 2024-09-25 22:58 UTC
